/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BienvenueRouteImport } from './routes/bienvenue'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as RestaurantIdRouteImport } from './routes/restaurant.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenueRoute = BienvenueRouteImport.update({
  id: '/bienvenue',
  path: '/bienvenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantIdRoute = RestaurantIdRouteImport.update({
  id: '/restaurant/$id',
  path: '/restaurant/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bienvenue': typeof BienvenueRoute
  '/conditions': typeof ConditionsRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/panier': typeof PanierRoute
  '/restaurant/$id': typeof RestaurantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bienvenue': typeof BienvenueRoute
  '/conditions': typeof ConditionsRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/panier': typeof PanierRoute
  '/restaurant/$id': typeof RestaurantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bienvenue': typeof BienvenueRoute
  '/conditions': typeof ConditionsRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/panier': typeof PanierRoute
  '/restaurant/$id': typeof RestaurantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bienvenue'
    | '/conditions'
    | '/connexion'
    | '/inscription'
    | '/panier'
    | '/restaurant/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bienvenue'
    | '/conditions'
    | '/connexion'
    | '/inscription'
    | '/panier'
    | '/restaurant/$id'
  id:
    | '__root__'
    | '/'
    | '/bienvenue'
    | '/conditions'
    | '/connexion'
    | '/inscription'
    | '/panier'
    | '/restaurant/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BienvenueRoute: typeof BienvenueRoute
  ConditionsRoute: typeof ConditionsRoute
  ConnexionRoute: typeof ConnexionRoute
  InscriptionRoute: typeof InscriptionRoute
  PanierRoute: typeof PanierRoute
  RestaurantIdRoute: typeof RestaurantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenue': {
      id: '/bienvenue'
      path: '/bienvenue'
      fullPath: '/bienvenue'
      preLoaderRoute: typeof BienvenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$id': {
      id: '/restaurant/$id'
      path: '/restaurant/$id'
      fullPath: '/restaurant/$id'
      preLoaderRoute: typeof RestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BienvenueRoute: BienvenueRoute,
  ConditionsRoute: ConditionsRoute,
  ConnexionRoute: ConnexionRoute,
  InscriptionRoute: InscriptionRoute,
  PanierRoute: PanierRoute,
  RestaurantIdRoute: RestaurantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
